### ISSUE TITLE
Prebuilt binaries for Windows

### ISSUE THREAD

**Issue by reza-ebrahimi** [h4tr3d/cmakeprojectmanager2#12]
There is no prebuilt binaries for Windows platform.

**Comment by h4tr3d** [comment]
Your solution is welcomed :-) I am not us QtC-git at the Windows at all, my main platform is Linux. You can do it as an external project like Zaranoe FFmpeg: https://ffmpeg.zeranoe.com/builds/

UPD sorry about AvCpp :-)

**Comment by h4tr3d** [comment]
Also, without version fixation it is too difficult to provide binaries for Latest QtC: it change API too quickly :-( I plan to prepare "stable" branch for official QtC versions begin from 4.3: API will be freeze and it is possible to shipment binary version for many platforms. In theory.

Another issue, binary builds for QtC latest on download.qt.io does not contains headers/private headers to build plugins. So, it is impossible to get such binary installation and build plugin for them.

**Comment by reza-ebrahimi** [comment]
@h4tr3d Your plan is welcome :)
