### ISSUE TITLE
Undefined reference compilation errors

### ISSUE THREAD

**Issue by RicBent** [h4tr3d/cmakeprojectmanager2#14]
I am using this version of Qt Crator: https://aur.archlinux.org/packages/qtcreator-git/
Apart from my current version I tried almost every version I could find but allways get these errors:

![alt text](https://i.imgur.com/PW5IJG2.png "Compilation Errors")

**Comment by h4tr3d** [comment]
Hi, just wait. Master branch changes API so quickly, I sync code base time or two in month (I has no more time for them). If you use QtC from AUR you can try to use https://aur.archlinux.org/packages/qtcreator-opt-git/ and https://aur.archlinux.org/packages/qtcreator-cmakeprojectmanager2-plugin-opt-git/ that synced and compatible by API.

**Comment by h4tr3d** [comment]
Hi, just wait. Master branch changes API so quickly, I sync code base time or two in month (I has no more time for them). If you use QtC from AUR you can try to use https://aur.archlinux.org/packages/qtcreator-opt-git/ and https://aur.archlinux.org/packages/qtcreator-cmakeprojectmanager2-plugin-opt-git/ that synced and compatible by API.

**Comment by RicBent** [comment]
Ah, thank you very much. I only found another strange version of your plugin on aur (that was a bit old).

Everything seems to work fine. But there seems to be the bug that QtC doesn't seem to be able to run the executable correctly. The executables are compiled correctly in the specified build dir but QtC errors with "Executable ProjectTitleGoesHere does not exist."

The working director for "Run" is by default set to a temp dir "/tmp/QtCreator-vguagO/qtc-cmake-XXGOtl5Y".
But even when setting the working dir to the actual build dir which contains the executable it still errors with "Executable  ProjectTitleGoesHere does not exist."

**Comment by RicBent** [comment]
Well, I got it working by adding a new run config with custom executable and setting the executable name to the project name and the working dir to "%{buildDir}". My custom config is entirely identical to the default one, but the defaut one somehow allways tries to run the executable from my home dir? Strange.

**Comment by h4tr3d** [comment]
@RicBent, could you please create another report for executable issue? Look like upstream regression, but...
