### ISSUE TITLE
Default run configuration problem

### ISSUE THREAD

**Issue by RicBent** [h4tr3d/cmakeprojectmanager2#15]
When creating a new project with this project manager and running it after building, the 'Application Output' reports "Executable cmakeTest does not exist.".

When going to the "Projects" tab in QtC and then clicking on the "Run" settings, the green build and run/debug buttons go grey and it displays the warning "The project no longer builds the target associated with this run configuration." under the the run config selector.

After selecting any other build configuration the warning disappears.
The working dir of the run config is set to a temp dir ("/tmp/QtCreator-sxApBH/qtc-cmake-XXqgzBa4" for example) which never exists. Even when setting that path to the build dir it still fails to find the executable.

The only method I found to get arrount the error is adding a new run config (Add -> Custom Executable), setting the executable to the project name and the working dir to "%{buildDir}".

**Comment by h4tr3d** [comment]
Hi @RicBent!

Could you please recheck latest version? Some amount of problems with run configuration was fixed by upstream, so, possible it fixed here too :-)

Thanks!

**Comment by h4tr3d** [comment]
I close issue due to no feedback.
