### ISSUE TITLE
Cannot build because it cannot find app/appversion.h

### ISSUE THREAD

**Issue by linux4hach** [h4tr3d/cmakeprojectmanager2#16]
I tried to build according to your instructions.   One difference is I have llvm50 and do not have llvm39 on my box...thought it may cause me problems perhaps it did?   Here is what I did

2151  qmake IDE_PACKAGE_MODE=1 PREFIX=/opt/qtcreator-git LLVM_INSTALL_DIR=/usr/lib/llvm-5.0 CONFIG+=qbs_enable_project_file_updates /tmp/qt-creator/qt-creator/qtcreator.pro 
 2152  ls
 2153  make -j13
 2154  ls
 2155  sudo make install
 2156  cd /tmp/qt-creator
 2157  ls
 2158  git clone git@github.com:h4tr3d/cmakeprojectmanager2.git
 2159  ls
 2160  makedir cmakeprojectmanager2-build
 2161  mkdir cmakeprojectmanager2-build
 2162  cd cmakeprojectmanager2-build/
 2163  ls
 2164  cd ..
 2165  sl
 2166  ls
 2167  mv cmakeprojectmanager2 cmakeprojectmanager2-git
 2168  ls
 2169  cd cd cmakeprojectmanager2-build
 2170  cd cmakeprojectmanager2-build/
 2171  qmake QTC_PREFIX=/opt/qtcreator-git
 2172  qmake QTC_PREFIX=/opt/qtcreator-git \
 2173  export QTC_SOURCE=/tmp/qt-creator/qt-creator
 2174  export QTC_BUILD=/opt/qtcreator-git
 2175  qmake QTC_PREFIX=/opt/qtcrator-git \
 2176  qmake QTC_PREFIX=/opt/qtcreator-git LIBS+=-L${QTC_BUILD}/lib/qtcreator LIBS+=-L${QTC_BUILD}/lib/qtcreator/plugins ../cmakeprojectmanager2-git/cmakeprojectmanager.pro 
 2177  make -j13
 (of course including my screwups)...I got a compile that looked pretty good initially until....
../cmakeprojectmanager2-git/cmakekitinformation.cpp:32:10: fatal error: app/app_version.h: No such file or directory
 #include <app/app_version.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:3465: .obj/release-shared/cmakekitinformation.o] Error 1
make: *** Waiting for unfinished jobs....

Which made me think that app/app_version.h was likely no longer in the current source for qtcreator....are you still using this tool, or am I going on a bug chase of my own?

Thanks!
Chris

**Comment by h4tr3d** [comment]
Hi, this file generates during QtC configuration process. Look for WA:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qtcreator-opt-git#n92

**Comment by linux4hach** [comment]
Alexander,


Thanks!  I use Manjaro (arch based incase you don't know...which I bet you do) so I can just use your pkgconfigs to do the build.  I am glad you have them there.   Once it is build I should be able to distribute the one made in the opt prefix to my other users.   I have a lot of developers who are "married" to using IDEs.  I tend to use vim for my development so I don't really need it at all strictly speaking.  The problem is when I wrote a cmake build system for our project, qtcreator wasn't letting them add files (as you no doubt know)...so their conclusion was CMAKE cannot be used...but that makes CI super easy so I was looking at a way to keep the IDE users happy, hopefully your pkgconfigs will let me do that for them.  Unfortunately I am the only one using an arch based distro.  They are all super linux noobs and will ONLY use mint and the PPAs for your plugin are out of date for the most current one.


I just tried it....and it works great.   I am assuming you use arch and you maintain the pkgconfig on the aur for your use?


BTW...I am not thinking wrong?....I should be able to tarball everything under opt/qtcreator-git and distribute it and it ought to work? (I may need to bundle some of my .so files I'd guess).




Anyway...thanks a bunch have a great week.



Chris

________________________________

**Comment by h4tr3d** [comment]
> I am assuming you use arch and you maintain the pkgconfig on the aur for your use?

You are right ;-) I am on Manjaro now. Currently I have no time to update PKGBUILDs for QtC and plugin. Seems I do it during this week.

PPA was prepared for my Mint setups. But I migrate to the Manjaro: mint moves to systemd too, but Arch-like build specs and pacman more comfortable for me.

> BTW...I am not thinking wrong?....I should be able to tarball everything under opt/qtcreator-git and distribute it and it ought to work? (I may need to bundle some of my .so files I'd guess).

It more complex process. Best solution, prepare setup using Docker and CentOS 6 (for example: https://github.com/h4tr3d/holy-build-box/tree/split+gcc7+dyn) and prepare deployment script using linuxdeployqt and some manual impact. In such case you can prepare tar.gz bundle and distribute across multiple Linux distros. Note, CentOS 6 selected because contains so old glibc: all modern systems contains more never one and glibc provides best ABI compatibility, so all applications built with old glibc will be work with newer one. While so-name will be kept unchanged :-)

I use such way to prepare multi-distro binary distribution for company product. But it also will be packed to the AppImage. But it is optional step.

**Comment by linux4hach** [comment]
Thanks Alexander, first for making the plugin available publically in the first place and second for your assistance.   I just discovered Docker last week, and I am a little weak on it... thanks for the link I will set up a docker for this then that I can distribute.   For some reason when I pass in PREFIX to qmake it isn't building in the prefix that I have selected.   I don't understand why it isn't...but that was what was giving me grief, hopefully the build works better in the centos docker.


Thanks!



________________________________
