### ISSUE TITLE
Precompiled releases

### ISSUE THREAD

**Issue by akontsevich** [h4tr3d/cmakeprojectmanager2#17]
Could You make precompiled releases for CMakeProjectManager2 like qtc-gtest (Qt Creator Google Test framework integration plugin) do: https://github.com/OneMoreGres/qtc-gtest/releases? Thanks!

**Comment by h4tr3d** [comment]
No. I just has no resources for it. Any help welcomed.

**Comment by akontsevich** [comment]
Was able to build for latest Qtc 4.5, failed for 4.4 however:
```
./cmakeprojectmanager2/cmakebuildtarget.h:30:10: 
fatal error: projectexplorer/projectmacro.h: No such file or dir
 #include <projectexplorer/projectmacro.h>
```
Good to have prebuilt. It is a pity that You can't.

**Comment by h4tr3d** [comment]
master branch just related to the master branch of QtC. There is a lot of changes between 4.4 and master. QtC does not provide stable plugin API due to single major (4.x) version at all :-(

**Comment by h4tr3d** [comment]
I was plane to make tags/branches for related  QtC versions but... currently I have no time at all :-( work, small son. I just update ArchLinux specs in AUR both for plugin and QtC.

**Comment by akontsevich** [comment]
> currently I have no time at all :-( work, small son. 

Same thing: want to do all and know all, but time... :) Hope will accept and process information faster in the future :)
