### ISSUE TITLE
Not an issue, a question, in fact.

### ISSUE THREAD

**Issue by shujaatak** [h4tr3d/cmakeprojectmanager2#20]
Can you please mention which distro and desktop environment you use? I saw screenshots on your website and I got amazed how beautiful looking it is!
Link to your post is: https://htrd.su/blog/2020/01/16/firefox-72-disable-tab-scrolling/

**Comment by h4tr3d** [comment]
Hi, Manjaro Linux and KDE. Look&Feel configuration near to default one :-) Breath, Application L&F Breeze, GTK2/3 - Breath, Mouse cursors - Bluecurve.
