### ISSUE TITLE
Steps duplicated

### ISSUE THREAD

**Issue by sr-tream** [h4tr3d/cmakeprojectmanager2#22]
After opening an existing CMake project (created without this plugin), steps build and clean are duplicated.

QtCreator: 6.0.0-beta1 (5.82.0)
This plugin: [a82221f](https://github.com/h4tr3d/cmakeprojectmanager2/commit/a82221f66120e1e17c373d4b577b84d7cb39bd1a)

Projects created with plugin not tested.

**Comment by h4tr3d** [comment]
Hmm... I can't observe such behavior on my projects. Could you please provide detailed steps for reproduction?

**Comment by sr-tream** [comment]
1. Create CMake project without plugin
2. Enable plugin
3. Open project

P.S. builtin CMake plugin not disabled

**Comment by sr-tream** [comment]
> P.S. builtin CMake plugin not disabled

Yeah, it's a problem, after disabling all work is fine

**Comment by h4tr3d** [comment]
> Yeah, it's a problem, after disabling all work is fine

Yes, it is matter. I didn't found any solution yet to work without turning off original plugin. There is at least one disadvantage of this: some plugins depends now on original plugin
